# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af848513e8d94b5cd3566ccc7fa59af15c4d031a1d406bf34dd5f051a9d31c7768d9a704a807a35adb2b0afbb74c1950b3f76ad71ae800805fac9c91b58e839f

test:
  secret_key_base: 22d2e1a290e663e240212d9d7d04250b7d5afa5b30f1748d632af62ef0ebf48f2dabaac0095fbda7096a332d21c3bd11537291c0d14f8d0ad140883481653295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
