# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f67dbe6d97f335fd77faac69ff9eed40389eba122e1e470c668f173a97ba13af01856e3e753e375a15d0d454f0440b9c939ea0668001c7b7bf1e9c1c4e97d4a9

test:
  secret_key_base: c878daad008b273d33f6a0070d403db183b8d5f015b34b8d487c36262e43df8a1d564f26e0cdedb87405f63a9ebb84ca470caebb31170d233ca0e40a146571cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
