# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d54d05d9fa3899383e3cf886c5ae2184395cd11c2e681f817bcfb6fcd7c1037ac760cd223f19e36b50d7ba5bac94bd264aa347eb7d17df8a24056af6608cb26

test:
  secret_key_base: 786c6ef2a86af99ef7eac9c3ea5b4e3968ddce5be8488b344db6f4fe347fff70c9997bf02196360788d8381b424bc5931016260fde1f58f9d9c6b3ed8b345c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
